### ISSUE TITLE
How do you test it

### ISSUE THREAD

**Issue by marregui** [TopchetoEU/java-jscript#21]
I have noticed that there aren't any tests, do you keep a separate repo?

**Comment by TopchetoEU** [comment]
i haven't gotten to writting tests yet, but that's definitely on the roadmap

**Comment by marregui** [comment]
I have pushed PR https://github.com/TopchetoEU/jscript/pull/23 with the first test, following gradle conventions.

**Comment by marregui** [comment]
thank you for merging!
